server {
    listen 80;
    listen [::]:80;
    server_name lifeman.dzfee.id;

    root /home/lexx/lifeman/public;
    index index.php;

    client_max_body_size 8M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.5-fpm.sock;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    location ~* \.(?:js|css|woff2?|ttf|otf|svg|png|jpg|jpeg|gif|webp|ico|map)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }
}